### ISSUE TITLE
Creat slug generator for connect. 

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/connect#270]
1. Slug Generator for URLs: Develop a slug generator to replace URL-encoded characters like "%20" with more user-friendly alternatives. This could improve the user interface by making URLs more readable and less intimidating.
2. Clear Storage Action: Modify the clear storage action to also clear the URL, as the current URL points to non-existent data after the storage is cleared.

#205 Is related and could be tackled together

**Comment by CallmeT-ty** [comment]
@ryanwolhuter Another Issue related to URL's. If relevant to the current topic you are working on, please feel free to assign to yourself or close/update/merge.

**Comment by ryanwolhuter** [comment]
> @ryanwolhuter Another Issue related to URL's. If relevant to the current topic you are working on, please feel free to assign to yourself or close/update/merge.

I was not planning on building the slug generator itself, I was going to rely on IDs and then if there is a slug we can use instead, then I would use that. 

I think the slug generator is its own beast.
