### ISSUE TITLE
Detect version differences and prompt page refresh

### ISSUE THREAD

**Issue by CallmeT-ty** [powerhouse-inc/connect#341]
This will deal with all cases were people have different version of connect, unknowning they need to refresh.

- Whenever there is a synch error, if dependencies & version are not similar => display toaster with instant refresh link. 
- API endpoint fetches the version for comparison

DoD
- Toast is implemented and available on Powerhouse Production
- Should be pushed to all staging environments

**Comment by froid1911** [comment]
- added / reactivated versioning for connect and switchboard
- this can be used to detect the loaded version and the latest version in github

**Comment by CallmeT-ty** [comment]
Now up to the front end team to load the versioning in connect & show a toast when connect & switchboard are out of sync.

**Comment by wkampmann** [comment]
I saw this notification pop up now in the dev environment. We should do 2 more things to make this work: 

- This notification should be persistent. The toaster shouldn't close until the user closes it.
- We need a way to test this that doesn't involve having to actually deploy a new client version or something. Let's brainstorm on the best way to do this. 

On a more general note, testability should be part of our definition of done by default. For some features it may well be more work to make the feature testable than to do the actual implementation.

**Comment by CallmeT-ty** [comment]
Given todays issues, we'll have to see if the frequency sholuldn't be controled. Likely making it persistent will be enough.

**Comment by wkampmann** [comment]
Observing it more, I think the trigger condition needs to be improved too. 

https://github.com/powerhouse-inc/connect/assets/1241878/212ed818-9024-468e-b8eb-0c437f013a5f

From this recording it's clear that the toaster is triggered by an unrelated error.

**Comment by CallmeT-ty** [comment]
When we deploy switchboard & connect. Both usually get deployed with same doc mod libs & doc drive. But they have different versions on their own. We can define a minimum version, not the exact version. 

- [ ] Research needed to figure out if we can get the specific version in the log file for the document drive server. (both on connect & switchboard side).
- [ ] Add a version fingerprint hash to the response headers of switchboard. 
- [ ] update the version info endpoint to reflect the locked packaged versions instead of packed json version constraints
- [ ] When connect encounters a new hash it should fetch the detailed version information from switchboard
- [ ] If the switchboard version are more recent then the connect version it should prompt the user to refresh the browser.
