### ISSUE TITLE
Improve FolderView performance

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/connect#357]
A folder with many files is causing the UI to become unresponsive when it rerenders

We should rely heavily in memorization to avoid rerendering all the file items.

Each FileItem has some costly methods being called during render time:
- getReadableItemPath
- decodeID
We should take the chance to optimize these methods for performance.

If needed, we could also add virtualization to only render the visible section of the file list.

DOD
- Should be deployed to development 
- Test 1000's of files in a single folder, navigate the folder without issues

![Image](https://github.com/powerhouse-inc/connect/assets/5501872/261dd2a1-40c8-4e63-954c-0e4102da25a6)

![Image](https://github.com/powerhouse-inc/connect/assets/5501872/59e469ee-faad-4510-8ac2-a3bb61b05f71)

**Comment by CallmeT-ty** [comment]
T will actually do the test and confirm

**Comment by CallmeT-ty** [comment]
I can create a 100 files, but not 1000 since i'm only able to duplicate 1 file at a time...
