### ISSUE TITLE
Force page refresh when a new version of connect is deployed

### ISSUE THREAD

**Issue by acaldas** [powerhouse-inc/connect#455]
If an user keeps Connect open in the browser, it might go out of date as we deploy new versions.
We need to add a check to ensure that users are in the latest available version.

Some possible approaches:
- Set cache headers to invalidate browser cache
- Add a way to check the latest version of Connect and check it regularly
- Use a Service Worker to do the version check?

**Comment by gpuente** [comment]
Hey @CallmeT-ty ! this one is already available for testing in development 👍🏻

**Comment by CallmeT-ty** [comment]
@acaldas Will test it next time something is pushed to develop
